### ISSUE TITLE
how to change the background color and text color?

### ISSUE THREAD

**Issue by realwqsz** [jraska/Console#22]
The idea of this view is great，I wonder if I  can change the background color and text color of the view, I didn't find any api or attribute I can set?

**Comment by jraska** [comment]
Hello,

for the change of text color there is:
```
Console.writeLine(spannableString: SpannableString?)
``` 
`SpannableString` could have text color, example using `ForegroundColorSpan` is in `ConsoleTree.createSpannable` method.


For changing the background color currently you can create custom `console_content` layout in your app and make the console look the way you want :)

**Comment by realwqsz** [comment]
It works，think you!
