### ISSUE TITLE
Is there a maximum of lines?

### ISSUE THREAD

**Issue by GuilhermeCouto** [jraska/Console#38]
Is there a maximum of lines?

Is there an option to set to free memory?

**Comment by jraska** [comment]
Hey Guilherme, there is a maximum size of the underlying buffer - 16k characters - see [here](https://github.com/jraska/Console/blob/8d10e4a8fe851b8600902636bf095ede03d2655d/console/src/main/java/com/jraska/console/ConsoleBuffer.kt#L60).

There is not a public option to set it.

**Comment by GuilhermeCouto** [comment]
So after this it will discard the old ones, right?

**Comment by jraska** [comment]
> So after this it will discard the old ones, right?

Correct :)
