### ISSUE TITLE
Enable text selection

### ISSUE THREAD

**Issue by jraska** [jraska/Console#4]
Text selection should be enabled on long click and scrolling postponed at that time. Until the end of selection mode.

**Comment by jraska** [comment]
As I think about it, only automated scrolling should be disabled, when user moves with finger downwards or upwards selection should scroll with console.

**Comment by mbeaty** [comment]
Just an FYI, I just grabbed a reference to the Console TextView and set textView.setTextIsSelectable(true) and that worked for my needs. I think that method is available for API 11+.
